server:
  port: 8090
spring:
  application:
    name: mybatis-dynamic-sql-hub
  datasource:
    dynamic:
      primary: all_in_one
      datasource:
        all_in_one:
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/all_in_one?characterEncoding=utf8&useSSL=false
        blog:
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/blog?characterEncoding=utf8&useSSL=false
  main:
    banner-mode: off
