/*
 * This file is generated by jOOQ.
 */
package org.tea.plus.jooq.sources;


import org.tea.plus.jooq.sources.tables.UserInfo;
import org.tea.plus.jooq.sources.tables.records.UserInfoRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * all-in-one.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<UserInfoRecord> KEY_USER_INFO_PRIMARY = Internal.createUniqueKey(UserInfo.USER_INFO, DSL.name("KEY_user_info_PRIMARY"), new TableField[] { UserInfo.USER_INFO.ID }, true);
}
