/*
 * This file is generated by jOOQ.
 */
package org.tea.plus.jooq.sources;


import org.tea.plus.jooq.sources.tables.UserInfo;


/**
 * Convenience access to all tables in all-in-one.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>all-in-one.user_info</code>.
     */
    public static final UserInfo USER_INFO = UserInfo.USER_INFO;
}
