spring:
  datasource:
    hikari:
      master:
        jdbc-url: jdbc:mysql://127.0.0.1:3306/all_in_one?characterEncoding=utf8&useSSL=false
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
      slave:
        jdbc-url: jdbc:mysql://127.0.0.1:3306/blog?characterEncoding=utf8&useSSL=false
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
